<a href="https://colab.research.google.com/github/Meenakrishnan-work/Meenakrishnan-work.github.io/blob/main/Unit_1_Lab_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
name = input("Enter your name: ")
age = int(input("Enter your age: "))
print("Student Name:", name)
print("Student Age:", age)

Enter your name: Keshika
Enter your age: 14
Student Name: Keshika
Student Age: 14


In [4]:
num = int(input("Enter a number: "))
if num % 2 == 0:
 print("Even Number")
else:
 print("Odd Number")

Enter a number: 25
Odd Number


In [6]:
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))
if a >= b and a >= c:
 print("Largest number is:", a)
elif b >= a and b >= c:
 print("Largest number is:", b)
else:
 print("Largest number is:", c)

Enter first number: 10
Enter second number: 25
Enter third number: 15
Largest number is: 25


In [7]:
for i in range(1, 11):
 print(i)

1
2
3
4
5
6
7
8
9
10


In [8]:
n = int(input("Enter a number: "))
sum = 0
for i in range(1, n + 1):
 sum = sum + i
print("Sum =", sum)

Enter a number: 5
Sum = 15


In [9]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print("NumPy Array:")
print(arr)

NumPy Array:
[10 20 30 40 50]


In [10]:
import numpy as np
a = np.array([10, 20, 30])
b = np.array([2, 4, 5])
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [12 24 35]
Subtraction: [ 8 16 25]
Multiplication: [ 20  80 150]
Division: [5. 5. 6.]


In [11]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print("First element:", arr[0])
print("Last element:", arr[-1])
print("Elements from index 1 to 3:", arr[1:4])

First element: 10
Last element: 50
Elements from index 1 to 3: [20 30 40]


In [12]:
import numpy as np
arr = np.array([[10, 20, 30],
[40, 50, 60]])
print("Array:")
print(arr)
print("Number of dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)
print("Item size:", arr.itemsize, "bytes")
print("Total bytes:", arr.nbytes)

Array:
[[10 20 30]
 [40 50 60]]
Number of dimensions: 2
Shape: (2, 3)
Size: 6
Data type: int64
Item size: 8 bytes
Total bytes: 48


In [13]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print("Sum:", np.sum(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

Sum: 150
Maximum: 50
Minimum: 10
Mean: 30.0
Standard Deviation: 14.142135623730951


In [14]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = arr.reshape(2, 3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [15]:
import pandas as pd
df = pd.read_csv("students.csv")
print(df.head(10))

     Name Department  Age  Marks
0    Arun        CSE   20     85
1    Bala         IT   21     72
2  Charan        CSE   20     91
3   Divya        ECE   22     65
4    Esha        CSE   21     88
5   Farah         IT   20     76
6   Gokul        ECE   21     95
7    Hari        CSE   22     69
8    Isha         IT   20     82
9    Jaya        CSE   21     90


In [16]:
import pandas as pd
df = pd.read_csv("students.csv")
print("Shape of dataset:", df.shape)
print("Column names:", df.columns)
print("\nStatistical Summary:")
print(df.describe())

Shape of dataset: (11, 4)
Column names: Index(['Name', 'Department', 'Age', 'Marks'], dtype='object')

Statistical Summary:
             Age      Marks
count  11.000000  11.000000
mean   20.909091  81.000000
std     0.831209   9.787747
min    20.000000  65.000000
25%    20.000000  74.000000
50%    21.000000  82.000000
75%    21.500000  89.000000
max    22.000000  95.000000


In [17]:
import pandas as pd
df = pd.read_csv("students.csv")
sorted_df = df.sort_values(by="Marks")
print(sorted_df)

      Name Department  Age  Marks
3    Divya        ECE   22     65
7     Hari        CSE   22     69
1     Bala         IT   21     72
5    Farah         IT   20     76
10   Kavin        ECE   22     78
8     Isha         IT   20     82
0     Arun        CSE   20     85
4     Esha        CSE   21     88
9     Jaya        CSE   21     90
2   Charan        CSE   20     91
6    Gokul        ECE   21     95


In [18]:
import pandas as pd
df = pd.read_csv("students.csv")
sorted_df = df.sort_values(by="Marks", ascending=False)
print(sorted_df)

      Name Department  Age  Marks
6    Gokul        ECE   21     95
2   Charan        CSE   20     91
9     Jaya        CSE   21     90
4     Esha        CSE   21     88
0     Arun        CSE   20     85
8     Isha         IT   20     82
10   Kavin        ECE   22     78
5    Farah         IT   20     76
1     Bala         IT   21     72
7     Hari        CSE   22     69
3    Divya        ECE   22     65


In [19]:
import pandas as pd
df = pd.read_csv("students.csv")
result = df[df["Marks"] >= 80]
print(result)

     Name Department  Age  Marks
0    Arun        CSE   20     85
2  Charan        CSE   20     91
4    Esha        CSE   21     88
6   Gokul        ECE   21     95
8    Isha         IT   20     82
9    Jaya        CSE   21     90


In [22]:
import pandas as pd
df = pd.read_csv("students.csv")
result = df[
(df["Department"] == "CSE") &
(df["Marks"] >= 80)
]
print(result)

Empty DataFrame
Columns: [Name, Department, Age, Marks]
Index: []
